

module.exports = {
    ClientEnum: {
        RESPONSE_CONNECTION_ERROR: "CONNECTION_ERROR",
        RESPONSE_SUCCESS: "SUCCESS",
        RESPONSE_DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
        RESPONSE_PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
        RESPONSE_EMAIL_MISMATCH: "EMAIL_MISMATCH",
        RESPONSE_OTP_MISMATCH: "OTP_MISMATCH",
        RESPONSE_EMAIL_TAKEN: "EMAIL_TAKEN",
        RESPONSE_PHONE_TAKEN: "PHONE_TAKEN",
        RESPONSE_INVALID_JWT_TOKEN: "INVALID_JWT_TOKEN",
        RESPONSE_INVALID_GOOGLE_TOKEN: "INVALID_GOOGLE_TOKEN",
        RESPONSE_INVALID_PHONE_TOKEN: "INVALID_PHONE_TOKEN",
        RESPONSE_GROUP_NOT_FOUND: "TEAM NOT FOUND",



        INSERT: 'INSERT',
        UPDATE: 'UPDATE',

    }
};
